apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.configMap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.configMap.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

data:
  {{- range $key, $val := .Values.configMap.data }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
