apiVersion: v1
kind: Pod
metadata:
  name: kaniko-test
  namespace: devops-tools
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--version"]
  restartPolicy: Never
