apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-credentials
  namespace: devops-tools
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHsNCiAgICAgICJhdXRoIjogImJXOW9ZVzFsWkdaaGQzcHBPbTF2STJWekxtTnZiVEV5TXc9PSINCiAgICB9DQogIH0NCn0NCg==

# [Convert]::ToBase64String([IO.File]::ReadAllBytes("E:\Projects\k8s-cluster\ci-cd\configs\config.json"))

# config.json
# {
#   "auths": {
#     "https://index.docker.io/v1/": {
#       "auth": "bW9oYW1lZGZhd3ppOm1vI2VzLmNvbTEyMw=="
#     }
#   }
# }