name: Deploy via ngrok-exposed Minikube

on:
  repository_dispatch:
    types: [deploy-microservice]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig (ngrok public API)
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl get nodes

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Deploy with Helm
        run: |
          helm upgrade ecommerce ./helm-chart \
            --namespace ecommerce \
            --install \
            --set ${{ github.event.client_payload.service }}.image.repository=docker.io/your-dockerhub-username/${{ github.event.client_payload.service }} \
            --set ${{ github.event.client_payload.service }}.image.tag=${{ github.event.client_payload.tag }} \
            --atomic
